Update master_chatbotteams.yml

diff --git a/.github/workflows/master_chatbotteams.yml b/.github/workflows/master_chatbotteams.yml
--- a/.github/workflows/master_chatbotteams.yml
+++ b/.github/workflows/master_chatbotteams.yml
@@ -29,19 +29,15 @@ jobs:
       
       - name: Install dependencies
         run: pip install -r requirements.txt
-        
-      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
 
       - name: Zip artifact for deployment
-        run: zip release.zip ./* -r
+        run: zip -r release.zip . -x "venv/*"
 
       - name: Upload artifact for deployment jobs
         uses: actions/upload-artifact@v4
         with:
           name: python-app
-          path: |
-            release.zip
-            !venv/
+          path: release.zip
 
   deploy:
     runs-on: ubuntu-latest
@@ -50,7 +46,7 @@ jobs:
       name: 'Production'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     permissions:
-      id-token: write #This is required for requesting the JWT
+      id-token: write
 
     steps:
       - name: Download artifact from build job
@@ -59,11 +55,17 @@ jobs:
           name: python-app
 
       - name: Unzip artifact for deployment
-        run: unzip release.zip
-        
-      - name: Add startup.sh to the deployment
-        run: cp /tmp/deployment/startup.sh /home/site/wwwroot/
-      
+        run: unzip release.zip -d /tmp/deployment
+
+      - name: Copy startup.sh to the web root
+        run: |
+          if [ -f /tmp/deployment/startup.sh ]; then
+            cp /tmp/deployment/startup.sh /home/site/wwwroot/
+          else
+            echo "startup.sh not found!"
+            exit 1
+          fi
+
       - name: Login to Azure
         uses: azure/login@v2
         with:
@@ -71,10 +73,9 @@ jobs:
           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6B60E18729D14282BC7175F47ABD1759 }}
           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_426BBC44A796430EA6CCD9A877EFD740 }}
 
-      - name: 'Deploy to Azure Web App'
+      - name: Deploy to Azure Web App
         uses: azure/webapps-deploy@v3
         id: deploy-to-webapp
         with:
           app-name: 'chatbotteams'
           slot-name: 'Production'
-          
